# Generated by Django 6.0.4 on 2026-05-09 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nombre',
        ),
    ]
