# Generated by Django 6.0.4 on 2026-05-09 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_usuario_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rol',
            old_name='nombre_rol',
            new_name='name',
        ),
    ]
