# Generated by Django 6.0.4 on 2026-05-10 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rol',
            table='accounts_rol',
        ),
    ]
