# Generated by Django 6.0.4 on 2026-06-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
