# Generated by Django 6.0.4 on 2026-06-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_deliveryevidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryevidence',
            name='evidence_type',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
