# Generated by Django 6.0.4 on 2026-06-06 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_deliveryevidence_evidence_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryevidence',
            name='evidence_type',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='deliveryevidence',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='orders.order'),
        ),
    ]
