# Generated by Django 6.0.4 on 2026-06-16 00:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_deliveryevidence_evidence_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="change_date",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="history",
            index=models.Index(
                fields=["order", "change_date"], name="orders_hist_order_i_67ee25_idx"
            ),
        ),
    ]
