# Generated by Django 6.0.4 on 2026-05-09 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='PackagedStock',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='packaged_stock', serialize=False, to='products.product')),
                ('available_stock', models.IntegerField()),
                ('allocated_stock', models.IntegerField()),
                ('minimum_stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RawStock',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='raw_stock', serialize=False, to='products.product')),
                ('quantity_kilogram', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
