# Generated by Django 6.0.4 on 2026-05-31 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='grams',
            field=models.IntegerField(default=0),
        ),
    ]
