# Generated by Django 6.0.4 on 2026-05-31 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_grams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawstock',
            name='quantity_kilogram',
        ),
        migrations.AddField(
            model_name='rawstock',
            name='total_grams',
            field=models.IntegerField(default=0),
        ),
    ]
